// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tutorial;

#nullable disable

namespace Tutorial.TutorialContext.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231109214328_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tutorial.Entitys.SuperHero", b =>
                {
                    b.Property<int>("SuperHeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperHeroId"));

                    b.Property<int>("SuperHeroAge")
                        .HasColumnType("int");

                    b.Property<string>("SuperHeroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperHeroId");

                    b.ToTable("SuperHeroes");
                });

            modelBuilder.Entity("Tutorial.Entitys.SuperPower", b =>
                {
                    b.Property<int>("SuperPowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperPowerId"));

                    b.Property<string>("FightingSkill")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuperHeroId")
                        .HasColumnType("int");

                    b.Property<string>("SuperPowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperPowerId");

                    b.HasIndex("SuperHeroId");

                    b.ToTable("SuperPowers");
                });

            modelBuilder.Entity("Tutorial.Entitys.SuperPower", b =>
                {
                    b.HasOne("Tutorial.Entitys.SuperHero", "SuperHero")
                        .WithMany("SuperPowers")
                        .HasForeignKey("SuperHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperHero");
                });

            modelBuilder.Entity("Tutorial.Entitys.SuperHero", b =>
                {
                    b.Navigation("SuperPowers");
                });
#pragma warning restore 612, 618
        }
    }
}
